version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: visitor_management
    ports:
      - "3306:3306"
