---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: visitor-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: visitor-app
  template:
    metadata:
      labels:
        app:  visitor-app
    spec:
      containers:
        - name:  visitor-app
          image: 047719646308.dkr.ecr.eu-west-2.amazonaws.com/visitor:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql"  
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"  
            - name: DB_PASSWORD
              value: "rootpassword" 
            - name: DB_NAME
              value: "visitor_management"  e


---


apiVersion: v1
kind: Service
metadata:
  name: visitor-app
spec:
  type: LoadBalancer 
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: visitor-app
